Update selenium-test.yml

diff --git a/.github/workflows/selenium-test.yml b/.github/workflows/selenium-test.yml
--- a/.github/workflows/selenium-test.yml
+++ b/.github/workflows/selenium-test.yml
@@ -21,7 +21,6 @@ jobs:
         uses: actions/setup-java@v2
         with:
           java-version: '17'
-          distribution: 'adopt'  # Specify the distribution here
 
       - name: Install Chrome and Firefox
         run: |
@@ -35,8 +34,16 @@ jobs:
       - name: Build with Maven and generate Surefire report
         run: mvn clean verify -Dsurefire.reportName=TEST-total
 
-      - name: Parse Surefire XML report
-        id: test-results
+      - name: List directory contents
+        run: ls -R
+
+      - name: Check Surefire XML report
         run: |
-          total_tests=$(grep -oP '(?<=<tests run=")\d+' target/surefire-reports/TEST-total.xml | tail -1)
-          echo "Total number of test cases: $total_tests"
+          if [[ -f "target/surefire-reports/TEST-total.xml" ]]; then
+            total_tests=$(grep -oP '(?<=<tests run=")\d+' target/surefire-reports/TEST-total.xml | tail -1)
+            echo "Total number of test cases: $total_tests"
+          else
+            echo "Surefire XML report not found. Directory contents:"
+            ls -l target/surefire-reports/
+            exit 1
+          fi
