add sandbox

diff --git a/.github/workflows/selenium-test.yml b/.github/workflows/selenium-test.yml
--- a/.github/workflows/selenium-test.yml
+++ b/.github/workflows/selenium-test.yml
@@ -23,24 +23,28 @@ jobs:
           distribution: 'adopt'
           architecture: 'x64'
 
-      - name: Set up ChromeDriver and GeckoDriver
+      - name: Install Chrome and Firefox
         run: |
-          CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
-          wget -qP /tmp https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
-          unzip -q /tmp/chromedriver_linux64.zip -d /tmp
-          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
-          sudo chmod +x /usr/local/bin/chromedriver
+          sudo apt-get update
+          sudo apt-get install -y firefox
+          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
+          sudo apt-get update
+          sudo apt-get install -y google-chrome-stable
 
-          GECKO_DRIVER_VERSION=$(curl -sS https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")')
-          wget -qO /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/$GECKO_DRIVER_VERSION/geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz
-          tar -xzf /tmp/geckodriver.tar.gz -C /tmp
-          sudo mv /tmp/geckodriver /usr/local/bin/geckodriver
-          sudo chmod +x /usr/local/bin/geckodriver
 
-      - name: Run Selenium Tests
-        run: mvn clean verify
+      - name: Build with Maven and generate Surefire report
+        run: mvn clean verify -Dsurefire.reportName=TEST-total
 
-      - name: Print Maven test results directory
+
+
+      - name: Check Surefire XML report
         run: |
-          echo "=== Maven Test Results Directory ==="
-          echo "target/surefire-reports"
+              if [[ -f "target/surefire-reports/TEST-total.xml" ]]; then
+                total_tests=$(grep -oP '(?<=<tests run=")\d+' target/surefire-reports/TEST-TestSuite.xml | tail -1)
+                echo "Total number of test cases: $total_tests"
+              else
+                echo "Surefire XML report not found. Directory contents:"
+                ls -l target/surefire-reports/
+                exit 1
+              fi
